### ISSUE TITLE
Quick instructions to compile

### ISSUE THREAD

**Issue by sogewasp** [lawrenceamer/0xsp-Mongoose#2]
Hello, I'm interested in this project, but I know little to nothing about Pascal, I'd like to play with the code and recompile the application myself (I also do it for every project on github, I never use precompiled binaries, at least on my host machine...).
So my question is is it possible for you to add instructions on how to compile the code? Possibly dependencies also :-)
Thanks mate

**Comment by sogewasp** [comment]
Ok I found how to compile, I had to use Lazarus IDE.
The process is pretty straightforward, install, open project then build.
Still I find this very exotic, didn't know Pascal is still alive :-O

**Comment by lawrenceamer** [comment]
you can also contribute by sending pull requests , any improvements are very welcomed
