### ISSUE TITLE
Application Login Error

### ISSUE THREAD

**Issue by sogewasp** [lawrenceamer/0xsp-Mongoose#3]
Hello,

I've tried to configure the application but I've been unsuccessful so far.
I copied `web application` folder's content into `/var/www/html/0xsp/`, then added mysql credentials into `application/config/database.php`, accessed into the login page with user `admin` and password `0xsp` (found on file `0xsp.sql`), but then the application crashes with an error:

![0xsp_Error](https://user-images.githubusercontent.com/52079194/60671118-ae586600-9e72-11e9-808a-f2877998041d.png)

I've looked forward to fix the issue but I didn't find any solution.
The `dologin` function seems to be in the file `application/controllers/Login.php` but the application looks for `login/dologin` which does not exists.

I also noticed that the webapp has been built with CodeIgniter (v1.0 ?), but I didn't find any solution looking at his source code.

So I'm stuck now..
Have you any solution to this?

**Comment by lawrenceamer** [comment]
Hi , make sure to place .htaccess file on web application folder , if not available , make one with this code 
```
RewriteEngine On
RewriteCond %{REQUEST_FILENAME} !-f
RewriteCond %{REQUEST_FILENAME} !-d
RewriteRule ^(.*)$ index.php/$1 [L]
```

**Comment by sogewasp** [comment]
Thanks for the tip !

I also had to load the rewrite module in apache2:
```
#> a2enmod rewrite
```

then add those lines in the file `/etc/apache2/sites-available/000-default.conf` :
```
<Directory "/var/www/html">
    AllowOverride All
</Directory>
```
and restart apache2:
```
#> systemctl restart apache2
```

Then I had another Mysql error : `No Database selected`
So I configured Mysql and CodeIgnite to use the correct database"
```
#> mysql "yourdatabasename" < 0xsp.sql
```
And added database details in `application/config/database.php` : 
```
$db['default'] = array(
	'dsn'	=> '',
	'hostname' => 'localhost',
	'username' => 'yourdatabaseuser',
	'password' => 'yourdatabasepassword',
	'database' => 'yourdatabasename',
	'dbdriver' => 'mysqli',
	'dbprefix' => '',
	'pconnect' => FALSE,
	'db_debug' => (ENVIRONMENT !== 'production'),
	'cache_on' => FALSE,
	'cachedir' => '',
	'char_set' => 'utf8',
	'dbcollat' => 'utf8_general_ci',
	'swap_pre' => '',
	'encrypt' => FALSE,
	'compress' => FALSE,
	'stricton' => FALSE,
	'failover' => array(),
	'save_queries' => TRUE
);
```

Hope those information will be useful.

**Comment by wojiushixiaobai** [comment]
How to write nginx rewrite rules

**Comment by lawrenceamer** [comment]
> How to write nginx rewrite rules

since the web application is made by codeigniter you can check up their solution to do it also . https://www.nginx.com/resources/wiki/start/topics/recipes/codeigniter/

**Comment by zux0x3a** [comment]
the newer version supports node js, which is compatible with any operating system.
